# ---

# - name: Stop postgres container
#   containers.podman.podman_pod:
#     name: {{ POSTGRES_CONTAINER_NAME }}
#     state: stopped

# - name: Systemd unit files for postgres container must exist
#   containers.podman.podman_generate_systemd:
#     name: postgres_local
#     dest: ~/.config/systemd/user/

# - name: Postgres container must be started and enabled on systemd
#   ansible.builtin.systemd:
#     name: container-postgres_local
#     daemon_reload: yes
#     state: started
#     enabled: yes


# # Generate the unit files, but store them on an Ansible variable
# # instead of writting them on target host
# - name: Systemd unit files for postgres container must be generated
#   containers.podman.podman_generate_systemd:
#     name: postgres_local
#   register: postgres_local_systemd_unit

# # Generate the unit files with environment variables sets
# - name: Systemd unit files for postgres container must be generated
#   containers.podman.podman_generate_systemd:
#     name: postgres_local
#     env:
#       POSTGRES_USER: my_app
#       POSTGRES_PASSWORD: example
#   register: postgres_local_systemd_unit